package com.testcaseiq.api.audit;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    STORY_CREATED,
    STORY_UPDATED,
    STORY_DELETED,
    STORY_ANALYSIS_REQUESTED,
    TEST_GENERATION_REQUESTED,
    TEST_CASE_STATUS_CHANGED,
    TEST_CASE_UPDATED,
    TESTS_EXPORTED,
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED
}
