package com.testcaseiq.api.export.service;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Set;

import org.springframework.stereotype.Component;

import com.testcaseiq.api.domain.enums.TestCaseType;
import com.testcaseiq.api.domain.enums.TestLayer;
import com.testcaseiq.api.export.dto.ApprovedTestCaseExport;
import com.testcaseiq.api.export.dto.ExportedTestData;
import com.testcaseiq.api.export.dto.ExportedTestStep;
import com.testcaseiq.api.export.dto.TestCaseExportDocument;

/**
 * Generates a Playwright TypeScript skeleton (.spec.ts) from approved test cases.
 * Output is a draft scaffold — review required before execution.
 */
@Component
public class PlaywrightScriptGenerator {

    private static final String RULE =
            " * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━";

    private static final Set<TestLayer> NON_UI_LAYERS = Set.of(
            TestLayer.API, TestLayer.DATABASE, TestLayer.UNIT
    );

    public String generate(TestCaseExportDocument document) {
        StringBuilder out = new StringBuilder();
        appendFileHeader(out, document);
        out.append("import { test, expect } from '@playwright/test';\n\n");

        String describeTitle = document.testSuiteName() != null
                ? document.testSuiteName()
                : nullToEmpty(document.storyTitle());

        out.append("test.describe('").append(escape(describeTitle)).append("', () => {\n");

        if (document.testCases().isEmpty()) {
            out.append("\n  // No approved test cases found for this export.\n");
        } else {
            long skipped = document.testCases().stream().filter(this::isNonUi).count();
            out.append("\n  // Approved test cases: ").append(document.testCases().size()).append("\n");
            if (skipped > 0) {
                out.append("  // Non-UI test cases (stubbed with explanation): ").append(skipped).append("\n");
            }
            out.append("\n");

            for (ApprovedTestCaseExport tc : document.testCases()) {
                if (isNonUi(tc)) {
                    appendNonUiStub(out, tc);
                } else {
                    appendTest(out, tc);
                }
            }
        }

        out.append("});\n");
        return out.toString();
    }

    private void appendFileHeader(StringBuilder out, TestCaseExportDocument document) {
        String now = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'")
                .format(Instant.now().atOffset(ZoneOffset.UTC));

        out.append("/**\n");
        out.append(RULE).append("\n");
        out.append(" *  Generated by TestCaseIQ — Draft Automation Skeleton\n");
        out.append(RULE).append("\n");
        out.append(" *\n");
        out.append(" *  WARNING: This file requires review before execution.\n");
        out.append(" *\n");
        out.append(" *  - This is a scaffold, NOT production-ready automation.\n");
        out.append(" *  - Replace all TODO placeholders with real selectors and URLs.\n");
        out.append(" *  - Verify expected results match actual application behaviour.\n");
        out.append(" *  - Execute only in non-production environments.\n");
        out.append(" *  - All selectors marked 'replace-with-real-*' MUST be updated.\n");
        out.append(" *\n");
        out.append(" *  Story    : ").append(nullToEmpty(document.storyTitle())).append("\n");
        out.append(" *  Story ID : ").append(document.storyId()).append("\n");
        if (hasText(document.storyReference())) {
            out.append(" *  Reference: ").append(document.storyReference()).append("\n");
        }
        if (document.testSuiteId() != null) {
            out.append(" *  Suite    : ").append(nullToEmpty(document.testSuiteName())).append("\n");
        }
        out.append(" *  Exported : ").append(now).append("\n");
        out.append(RULE).append("\n");
        out.append(" */\n\n");
    }

    private void appendTest(StringBuilder out, ApprovedTestCaseExport tc) {
        String shortId = tc.testCaseId().toString().substring(0, 8).toUpperCase();
        String testName = shortId + " — " + nullToEmpty(tc.title());

        out.append("  test('").append(escape(testName)).append("', async ({ page }) => {\n");

        out.append("    // Objective       : ").append(nullToEmpty(tc.objective())).append("\n");
        out.append("    // Priority        : ").append(nullToEmpty(tc.priority())).append("\n");
        out.append("    // Risk            : ").append(nullToEmpty(tc.risk())).append("\n");
        out.append("    // Layer           : ").append(nullToEmpty(tc.layer())).append("\n");
        out.append("    // Automation      : ").append(tc.automationCandidate()).append("\n");
        if (hasText(tc.preconditions())) {
            out.append("    // Preconditions   : ").append(tc.preconditions()).append("\n");
        }
        if (tc.linkedRequirementReferences() != null && !tc.linkedRequirementReferences().isEmpty()) {
            out.append("    // Requirements    : ")
               .append(String.join(", ", tc.linkedRequirementReferences())).append("\n");
        }
        if (tc.sourceEvidence() != null && !tc.sourceEvidence().isEmpty()) {
            out.append("    // Source evidence : ")
               .append(String.join(", ", tc.sourceEvidence())).append("\n");
        }
        out.append("\n");

        if (hasText(tc.bddScenario())) {
            out.append("    /*\n");
            out.append("     * BDD Scenario:\n");
            for (String line : tc.bddScenario().split("\n", -1)) {
                out.append("     * ").append(line).append("\n");
            }
            out.append("     */\n\n");
        }

        if (tc.testData() != null && !tc.testData().isEmpty()) {
            out.append("    // Test data:\n");
            for (ExportedTestData td : tc.testData()) {
                out.append("    // const ").append(camelCase(td.name()))
                   .append(" = ").append(nullToEmpty(td.value())).append(";\n");
            }
            out.append("\n");
        }

        out.append("    // WARNING: replace placeholder selectors and URLs before execution.\n\n");
        out.append("    // TODO: Navigate to the relevant page.\n");
        out.append("    // await page.goto('/replace-with-real-url');\n");

        if (tc.steps() != null && !tc.steps().isEmpty()) {
            out.append("\n");
            for (ExportedTestStep step : tc.steps()) {
                out.append("    // Step ").append(step.order())
                   .append(": ").append(nullToEmpty(step.action())).append("\n");
                if (hasText(step.expectedResult())) {
                    out.append("    // Expected: ").append(step.expectedResult()).append("\n");
                }
                out.append("    // TODO: Implement step ").append(step.order()).append(".\n\n");
            }
        } else {
            out.append("\n");
        }

        if (hasText(tc.bddScenario())) {
            out.append("    // TODO: Assert: ").append(tc.bddScenario()).append("\n");
        } else {
            out.append("    // TODO: Add assertions.\n");
        }
        out.append("    // expect(page.locator('replace-with-real-selector')).toBeVisible();\n");
        out.append("  });\n\n");
    }

    private void appendNonUiStub(StringBuilder out, ApprovedTestCaseExport tc) {
        String shortId = tc.testCaseId().toString().substring(0, 8).toUpperCase();
        String layer = nullToEmpty(tc.layer());
        out.append("  // ────────────────────────────────────────────────────────────\n");
        out.append("  // SKIPPED — not suitable for Playwright UI export\n");
        out.append("  // Test case : ").append(shortId).append(" — ").append(nullToEmpty(tc.title())).append("\n");
        out.append("  // Layer     : ").append(layer)
           .append(" — not suitable for browser-based Playwright automation.\n");
        out.append("  // Action    : Review this test case with an appropriate framework (e.g. REST Assured, JUnit).\n");
        out.append("  // ────────────────────────────────────────────────────────────\n\n");
    }

    private boolean isNonUi(ApprovedTestCaseExport tc) {
        if (tc.layer() != null && NON_UI_LAYERS.contains(tc.layer())) {
            return true;
        }
        return tc.type() == TestCaseType.API;
    }

    private String escape(String value) {
        if (value == null) return "";
        return value.replace("\\", "\\\\").replace("'", "\\'");
    }

    private String camelCase(String name) {
        if (name == null || name.isBlank()) return "value";
        String[] parts = name.split("[-_ ]+");
        StringBuilder result = new StringBuilder(parts[0].toLowerCase());
        for (int i = 1; i < parts.length; i++) {
            if (!parts[i].isEmpty()) {
                result.append(Character.toUpperCase(parts[i].charAt(0)));
                if (parts[i].length() > 1) result.append(parts[i].substring(1).toLowerCase());
            }
        }
        return result.toString();
    }

    private String nullToEmpty(Object value) {
        return value == null ? "" : value.toString();
    }

    private boolean hasText(String value) {
        return value != null && !value.isBlank();
    }
}
