package com.testcaseiq.api.export.service;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Set;

import org.springframework.stereotype.Component;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.testcaseiq.api.domain.enums.TestCaseType;
import com.testcaseiq.api.domain.enums.TestLayer;
import com.testcaseiq.api.export.dto.ApprovedTestCaseExport;
import com.testcaseiq.api.export.dto.ExportedTestStep;
import com.testcaseiq.api.export.dto.TestCaseExportDocument;

/**
 * Generates a Postman Collection v2.1 JSON skeleton from approved test cases.
 * Output is a draft scaffold — review required before execution.
 */
@Component
public class PostmanCollectionGenerator {

    private static final String SCHEMA =
            "https://schema.getpostman.com/json/collection/v2.1.0/collection.json";

    private static final Set<TestLayer> API_LAYERS = Set.of(
            TestLayer.API, TestLayer.INTEGRATION, TestLayer.DATABASE
    );

    private final ObjectMapper objectMapper;

    public PostmanCollectionGenerator(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public String generate(TestCaseExportDocument document) {
        ObjectNode collection = objectMapper.createObjectNode();
        collection.set("info", buildInfo(document));
        collection.set("item", buildItems(document));

        try {
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(collection);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Failed to generate Postman collection", e);
        }
    }

    private ObjectNode buildInfo(TestCaseExportDocument document) {
        String now = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'")
                .format(Instant.now().atOffset(ZoneOffset.UTC));

        String collectionName = "TestCaseIQ — " + nullToEmpty(document.storyTitle());
        if (document.testSuiteName() != null) {
            collectionName += " / " + document.testSuiteName();
        }

        String description = "Generated by TestCaseIQ\n"
                + "Draft API test collection — review required before execution.\n\n"
                + "WARNING: This collection is a draft scaffold, NOT production-ready.\n"
                + "- Replace all TODO placeholders and {{baseUrl}} with real values.\n"
                + "- Verify all endpoints, methods, and assertions before running.\n"
                + "- Execute only in non-production environments.\n\n"
                + "Story    : " + nullToEmpty(document.storyTitle()) + "\n"
                + "Story ID : " + document.storyId() + "\n"
                + "Exported : " + now;

        ObjectNode info = objectMapper.createObjectNode();
        info.put("name", collectionName);
        info.put("description", description);
        info.put("schema", SCHEMA);
        return info;
    }

    private ArrayNode buildItems(TestCaseExportDocument document) {
        ArrayNode items = objectMapper.createArrayNode();

        if (document.testCases().isEmpty()) {
            items.add(buildNoApprovedCasesItem());
            return items;
        }

        for (ApprovedTestCaseExport tc : document.testCases()) {
            if (isApiOriented(tc)) {
                items.add(buildApiItem(tc));
            } else {
                items.add(buildDocOnlyItem(tc));
            }
        }

        return items;
    }

    private ObjectNode buildNoApprovedCasesItem() {
        ObjectNode item = objectMapper.createObjectNode();
        item.put("name", "[INFO] No approved API test cases found for this export");
        item.set("request", buildPlaceholderRequest(
                "No approved API-oriented test cases are available for Postman export."
        ));
        item.set("response", objectMapper.createArrayNode());
        item.set("event", objectMapper.createArrayNode());
        return item;
    }

    private ObjectNode buildApiItem(ApprovedTestCaseExport tc) {
        ObjectNode item = objectMapper.createObjectNode();
        item.put("name", nullToEmpty(tc.title()));
        item.set("request", buildRequest(tc));
        item.set("response", objectMapper.createArrayNode());
        item.set("event", buildTestEvents(tc));
        return item;
    }

    private ObjectNode buildDocOnlyItem(ApprovedTestCaseExport tc) {
        String layer = nullToEmpty(tc.layer());
        String description = "[DOC ONLY] This test case is not suitable for direct Postman API export (layer: " + layer + ").\n"
                + "It has been included as a documentation reference only.\n\n"
                + "Consider using an appropriate framework (e.g. Playwright, Selenium) for this test case.\n\n"
                + "Objective : " + nullToEmpty(tc.objective()) + "\n"
                + "Priority  : " + nullToEmpty(tc.priority()) + "\n"
                + "Risk      : " + nullToEmpty(tc.risk()) + "\n"
                + "Layer     : " + layer + "\n";

        ObjectNode item = objectMapper.createObjectNode();
        item.put("name", "[DOC ONLY] " + nullToEmpty(tc.title()));
        item.set("request", buildPlaceholderRequest(description));
        item.set("response", objectMapper.createArrayNode());
        item.set("event", objectMapper.createArrayNode());
        return item;
    }

    private ObjectNode buildRequest(ApprovedTestCaseExport tc) {
        ObjectNode request = objectMapper.createObjectNode();
        request.put("method", "GET");
        request.set("header", buildTodoHeaders());
        request.set("url", buildUrl());
        request.put("description", buildDescription(tc));
        return request;
    }

    private ObjectNode buildPlaceholderRequest(String description) {
        ObjectNode request = objectMapper.createObjectNode();
        request.put("method", "GET");
        request.set("header", objectMapper.createArrayNode());
        request.set("url", buildUrl());
        request.put("description", description);
        return request;
    }

    private ObjectNode buildUrl() {
        ArrayNode host = objectMapper.createArrayNode();
        host.add("{{baseUrl}}");
        ArrayNode path = objectMapper.createArrayNode();
        path.add("replace-with-endpoint");

        ObjectNode url = objectMapper.createObjectNode();
        url.put("raw", "{{baseUrl}}/replace-with-endpoint");
        url.set("host", host);
        url.set("path", path);
        return url;
    }

    private String buildDescription(ApprovedTestCaseExport tc) {
        StringBuilder desc = new StringBuilder();
        desc.append("REVIEW REQUIRED before execution.\n\n");
        desc.append("Objective  : ").append(nullToEmpty(tc.objective())).append("\n");
        desc.append("Priority   : ").append(nullToEmpty(tc.priority())).append("\n");
        desc.append("Risk       : ").append(nullToEmpty(tc.risk())).append("\n");
        desc.append("Layer      : ").append(nullToEmpty(tc.layer())).append("\n");
        if (tc.sourceEvidence() != null && !tc.sourceEvidence().isEmpty()) {
            desc.append("Evidence   : ").append(String.join(", ", tc.sourceEvidence())).append("\n");
        }
        if (tc.linkedRequirementReferences() != null && !tc.linkedRequirementReferences().isEmpty()) {
            desc.append("Requirements: ").append(String.join(", ", tc.linkedRequirementReferences())).append("\n");
        }
        if (tc.steps() != null && !tc.steps().isEmpty()) {
            desc.append("\nManual steps:\n");
            for (ExportedTestStep step : tc.steps()) {
                desc.append("  ").append(step.order()).append(". ").append(nullToEmpty(step.action())).append("\n");
                if (step.expectedResult() != null && !step.expectedResult().isBlank()) {
                    desc.append("     Expected: ").append(step.expectedResult()).append("\n");
                }
            }
        }
        desc.append("\nTODO: Replace method, URL, headers, and body before execution.\n");
        desc.append("TODO: Replace {{baseUrl}} with the real base URL.\n");
        return desc.toString();
    }

    private ArrayNode buildTodoHeaders() {
        ObjectNode contentTypeHeader = objectMapper.createObjectNode();
        contentTypeHeader.put("key", "Content-Type");
        contentTypeHeader.put("value", "application/json");
        contentTypeHeader.put("description", "TODO: Update or remove this header as required");
        contentTypeHeader.put("disabled", true);

        ArrayNode headers = objectMapper.createArrayNode();
        headers.add(contentTypeHeader);
        return headers;
    }

    private ArrayNode buildTestEvents(ApprovedTestCaseExport tc) {
        ArrayNode exec = objectMapper.createArrayNode();
        exec.add("pm.test(\"TODO: validate expected result\", function () {");
        exec.add("    // TODO: Add assertions for this test case");
        exec.add("    // pm.response.to.have.status(200);");
        if (tc.steps() != null) {
            for (ExportedTestStep step : tc.steps()) {
                if (step.expectedResult() != null && !step.expectedResult().isBlank()) {
                    exec.add("    // Expected (step " + step.order() + "): " + step.expectedResult());
                }
            }
        }
        exec.add("});");

        ObjectNode script = objectMapper.createObjectNode();
        script.put("type", "text/javascript");
        script.set("exec", exec);

        ObjectNode event = objectMapper.createObjectNode();
        event.put("listen", "test");
        event.set("script", script);

        ArrayNode events = objectMapper.createArrayNode();
        events.add(event);
        return events;
    }

    private boolean isApiOriented(ApprovedTestCaseExport tc) {
        if (tc.layer() != null && API_LAYERS.contains(tc.layer())) {
            return true;
        }
        return tc.type() == TestCaseType.API;
    }

    private String nullToEmpty(Object value) {
        return value == null ? "" : value.toString();
    }
}
