package com.testcaseiq.api.export.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.testcaseiq.api.common.error.ResourceNotFoundException;
import com.testcaseiq.api.domain.enums.ExportStatus;
import com.testcaseiq.api.domain.enums.Priority;
import com.testcaseiq.api.domain.enums.ReviewStatus;
import com.testcaseiq.api.domain.enums.RiskLevel;
import com.testcaseiq.api.domain.enums.StoryType;
import com.testcaseiq.api.domain.enums.TestCaseType;
import com.testcaseiq.api.domain.enums.TestLayer;
import com.testcaseiq.api.domain.model.ExportJob;
import com.testcaseiq.api.domain.model.Project;
import com.testcaseiq.api.domain.model.Story;
import com.testcaseiq.api.domain.model.TestCase;
import com.testcaseiq.api.domain.model.TestData;
import com.testcaseiq.api.domain.model.TestStep;
import com.testcaseiq.api.domain.model.TestSuite;
import com.testcaseiq.api.domain.repository.ExportJobRepository;
import com.testcaseiq.api.domain.repository.StoryRepository;
import com.testcaseiq.api.domain.repository.TestSuiteRepository;
import com.testcaseiq.api.export.dto.ExportFormat;

@ExtendWith(MockitoExtension.class)
class PlaywrightExportServiceTests {

    @Mock
    private StoryRepository storyRepository;

    @Mock
    private TestSuiteRepository testSuiteRepository;

    @Mock
    private ExportJobRepository exportJobRepository;

    private ExportService exportService;

    @BeforeEach
    void setUp() {
        exportService = new ExportService(
                storyRepository,
                testSuiteRepository,
                exportJobRepository,
                new ObjectMapper(),
                new PlaywrightScriptGenerator()
        );
    }

    @Test
    void generatedFileContainsPlaywrightImport() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).contains("import { test, expect } from '@playwright/test';");
    }

    @Test
    void generatedFileContainsTestDescribeBlock() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).contains("test.describe(");
    }

    @Test
    void generatedFileContainsReviewRequiredWarning() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).containsIgnoringCase("review");
        assertThat(content).containsIgnoringCase("WARNING");
    }

    @Test
    void generatedFileContainsDraftSkeletonHeader() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).contains("Generated by TestCaseIQ");
        assertThat(content).contains("Draft Automation Skeleton");
    }

    @Test
    void approvedTestCaseIsIncludedAsTestBlock() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).contains("test('");
        assertThat(content).contains("Pay by card successfully");
    }

    @Test
    void rejectedTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).doesNotContain("Rejected card payment");
    }

    @Test
    void draftTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).doesNotContain("Draft payment test");
    }

    @Test
    void needsReviewTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).doesNotContain("Needs review payment test");
    }

    @Test
    void needsClarificationTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).doesNotContain("Needs clarification payment test");
    }

    @Test
    void apiLayerTestCaseIsStubbedNotDropped() {
        Story story = storyWithApiLayerTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).contains("SKIPPED");
        assertThat(content).contains("API endpoint health check");
        assertThat(content).doesNotContain("test('");
    }

    @Test
    void generatedFileIncludesTestStepsAsComments() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).contains("Submit valid card details");
        assertThat(content).contains("Payment is authorized");
    }

    @Test
    void generatedFileIncludesTestMetadata() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).containsIgnoringCase("Objective");
        assertThat(content).containsIgnoringCase("Priority");
        assertThat(content).containsIgnoringCase("Risk");
    }

    @Test
    void returnsCleanOutputWhenNoApprovedTestCasesExist() {
        Story story = storyWithOnlyDraftCases();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).content();

        assertThat(content).contains("import { test, expect } from '@playwright/test';");
        assertThat(content).contains("No approved test cases found");
        assertThat(content).doesNotContain("Draft only test");
    }

    @Test
    void createsCompletedExportJobForSuccessfulPlaywrightExport() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT);

        ArgumentCaptor<ExportJob> captor = ArgumentCaptor.forClass(ExportJob.class);
        verify(exportJobRepository).save(captor.capture());
        ExportJob job = captor.getValue();
        assertThat(job.getExportType()).isEqualTo("approved-test-cases-playwright");
        assertThat(job.getStatus()).isEqualTo(ExportStatus.COMPLETED);
    }

    @Test
    void throwsNotFoundWhenStoryDoesNotExist() {
        UUID storyId = UUID.randomUUID();
        when(storyRepository.findById(storyId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> exportService.exportStory(storyId, ExportFormat.PLAYWRIGHT))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessage("Story not found: " + storyId);
    }

    @Test
    void throwsNotFoundWhenTestSuiteDoesNotExist() {
        UUID testSuiteId = UUID.randomUUID();
        when(testSuiteRepository.findById(testSuiteId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> exportService.exportTestSuite(testSuiteId, ExportFormat.PLAYWRIGHT))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessage("Test suite not found: " + testSuiteId);
    }

    @Test
    void resultFilenameHasSpecTsExtension() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String filename = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).filename();

        assertThat(filename).endsWith(".spec.ts");
    }

    @Test
    void resultContentTypeIsTextPlain() {
        Story story = storyWithApprovedTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String contentType = exportService.exportStory(story.getId(), ExportFormat.PLAYWRIGHT).contentType();

        assertThat(contentType).isEqualTo("text/plain");
    }

    // ── Fixtures ──────────────────────────────────────────────────

    private Story storyWithApprovedTestCase() {
        Story story = new Story("Checkout payment", StoryType.USER_STORY);
        setId(story, UUID.randomUUID());
        story.setProject(new Project("Checkout Platform", "CHECKOUT"));

        TestSuite suite = new TestSuite("Checkout regression");
        setId(suite, UUID.randomUUID());

        TestCase approved = new TestCase("Pay by card successfully", TestCaseType.FUNCTIONAL);
        setId(approved, UUID.randomUUID());
        approved.setReviewStatus(ReviewStatus.APPROVED);
        approved.setDescription("Covers an approved card payment.");
        approved.setTestLayer(TestLayer.UI);
        approved.setPriority(Priority.HIGH);
        approved.setRiskLevel(RiskLevel.HIGH);
        approved.setAutomationCandidate(true);
        approved.setPreconditions("Buyer is signed in.");
        approved.setExpectedResult("Order confirmation displayed.");
        approved.addStep(new TestStep(1, "Submit valid card details", "Payment is authorized"));
        approved.addTestData(new TestData("validCard", "{\"number\":\"4111111111111111\"}"));

        suite.addTestCase(approved);
        story.addTestSuite(suite);
        return story;
    }

    private Story storyWithMixedStatuses() {
        Story story = storyWithApprovedTestCase();

        TestSuite suite = story.getTestSuites().getFirst();
        suite.addTestCase(nonApproved("Rejected card payment", ReviewStatus.REJECTED));
        suite.addTestCase(nonApproved("Draft payment test", ReviewStatus.DRAFT));
        suite.addTestCase(nonApproved("Needs review payment test", ReviewStatus.NEEDS_REVIEW));
        suite.addTestCase(nonApproved("Needs clarification payment test", ReviewStatus.NEEDS_CLARIFICATION));
        return story;
    }

    private Story storyWithOnlyDraftCases() {
        Story story = new Story("Checkout payment", StoryType.USER_STORY);
        setId(story, UUID.randomUUID());
        story.setProject(new Project("Checkout Platform", "CHECKOUT"));

        TestSuite suite = new TestSuite("Checkout regression");
        setId(suite, UUID.randomUUID());
        suite.addTestCase(nonApproved("Draft only test", ReviewStatus.DRAFT));
        story.addTestSuite(suite);
        return story;
    }

    private Story storyWithApiLayerTestCase() {
        Story story = new Story("Health check story", StoryType.USER_STORY);
        setId(story, UUID.randomUUID());
        story.setProject(new Project("API Platform", "API"));

        TestSuite suite = new TestSuite("API regression");
        setId(suite, UUID.randomUUID());

        TestCase apiCase = new TestCase("API endpoint health check", TestCaseType.FUNCTIONAL);
        setId(apiCase, UUID.randomUUID());
        apiCase.setReviewStatus(ReviewStatus.APPROVED);
        apiCase.setTestLayer(TestLayer.API);

        suite.addTestCase(apiCase);
        story.addTestSuite(suite);
        return story;
    }

    private TestCase nonApproved(String title, ReviewStatus status) {
        TestCase tc = new TestCase(title, TestCaseType.FUNCTIONAL);
        setId(tc, UUID.randomUUID());
        tc.setReviewStatus(status);
        return tc;
    }

    private void setId(Object entity, UUID id) {
        ReflectionTestUtils.setField(entity, "id", id);
    }
}
