package com.testcaseiq.api.export.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.testcaseiq.api.common.error.ResourceNotFoundException;
import com.testcaseiq.api.domain.enums.ExportStatus;
import com.testcaseiq.api.domain.enums.Priority;
import com.testcaseiq.api.domain.enums.ReviewStatus;
import com.testcaseiq.api.domain.enums.RiskLevel;
import com.testcaseiq.api.domain.enums.StoryType;
import com.testcaseiq.api.domain.enums.TestCaseType;
import com.testcaseiq.api.domain.enums.TestLayer;
import com.testcaseiq.api.domain.model.ExportJob;
import com.testcaseiq.api.domain.model.Project;
import com.testcaseiq.api.domain.model.Story;
import com.testcaseiq.api.domain.model.TestCase;
import com.testcaseiq.api.domain.model.TestStep;
import com.testcaseiq.api.domain.model.TestSuite;
import com.testcaseiq.api.domain.repository.ExportJobRepository;
import com.testcaseiq.api.domain.repository.StoryRepository;
import com.testcaseiq.api.domain.repository.TestSuiteRepository;
import com.testcaseiq.api.export.dto.ExportFormat;

@ExtendWith(MockitoExtension.class)
class PostmanExportServiceTests {

    @Mock
    private StoryRepository storyRepository;

    @Mock
    private TestSuiteRepository testSuiteRepository;

    @Mock
    private ExportJobRepository exportJobRepository;

    private ExportService exportService;

    @BeforeEach
    void setUp() {
        ObjectMapper objectMapper = new ObjectMapper();
        exportService = new ExportService(
                storyRepository,
                testSuiteRepository,
                exportJobRepository,
                objectMapper,
                new PlaywrightScriptGenerator(),
                new PostmanCollectionGenerator(objectMapper)
        );
    }

    @Test
    void generatedCollectionContainsPostmanSchemaInfo() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("schema.getpostman.com");
        assertThat(content).contains("v2.1.0");
    }

    @Test
    void generatedCollectionContainsCollectionName() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("Checkout payment");
    }

    @Test
    void generatedCollectionContainsItemArray() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("\"item\"");
    }

    @Test
    void generatedCollectionContainsBaseUrlPlaceholder() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("{{baseUrl}}");
    }

    @Test
    void generatedCollectionContainsReviewRequiredWarning() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).containsIgnoringCase("review required");
    }

    @Test
    void generatedCollectionContainsDraftHeader() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("Generated by TestCaseIQ");
        assertThat(content).contains("Draft API test collection");
    }

    @Test
    void approvedApiTestCaseIsIncludedAsItem() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("Verify API endpoint returns 200");
    }

    @Test
    void approvedApiTestCaseContainsTodoTestScript() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("pm.test");
        assertThat(content).contains("TODO");
    }

    @Test
    void rejectedTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).doesNotContain("Card payment rejected scenario");
    }

    @Test
    void draftTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).doesNotContain("Card payment draft scenario");
    }

    @Test
    void needsReviewTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).doesNotContain("Card payment needs-review scenario");
    }

    @Test
    void needsClarificationTestCaseIsExcluded() {
        Story story = storyWithMixedStatuses();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).doesNotContain("Card payment needs-clarification scenario");
    }

    @Test
    void approvedUiTestCaseIsIncludedAsDocOnlyNotDropped() {
        Story story = storyWithUiLayerTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("Login via browser UI");
        assertThat(content).contains("[DOC ONLY]");
    }

    @Test
    void handlesNoApprovedTestCasesCleanly() {
        Story story = storyWithOnlyDraftCases();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String content = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).content();

        assertThat(content).contains("schema.getpostman.com");
        assertThat(content).contains("item");
        assertThat(content).contains("No approved");
        assertThat(content).doesNotContain("Draft only API test");
    }

    @Test
    void throwsNotFoundWhenStoryDoesNotExist() {
        UUID storyId = UUID.randomUUID();
        when(storyRepository.findById(storyId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> exportService.exportStory(storyId, ExportFormat.POSTMAN))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessage("Story not found: " + storyId);
    }

    @Test
    void throwsNotFoundWhenTestSuiteDoesNotExist() {
        UUID testSuiteId = UUID.randomUUID();
        when(testSuiteRepository.findById(testSuiteId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> exportService.exportTestSuite(testSuiteId, ExportFormat.POSTMAN))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessage("Test suite not found: " + testSuiteId);
    }

    @Test
    void createsCompletedExportJobForSuccessfulPostmanExport() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        exportService.exportStory(story.getId(), ExportFormat.POSTMAN);

        ArgumentCaptor<ExportJob> captor = ArgumentCaptor.forClass(ExportJob.class);
        verify(exportJobRepository).save(captor.capture());
        ExportJob job = captor.getValue();
        assertThat(job.getExportType()).isEqualTo("approved-test-cases-postman");
        assertThat(job.getStatus()).isEqualTo(ExportStatus.COMPLETED);
    }

    @Test
    void resultFilenameContainsApprovedApiTestsAndPostmanExtension() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String filename = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).filename();

        assertThat(filename).startsWith("story-");
        assertThat(filename).contains("approved-api-tests");
        assertThat(filename).endsWith(".postman_collection.json");
    }

    @Test
    void resultContentTypeIsApplicationJson() {
        Story story = storyWithApprovedApiTestCase();
        when(storyRepository.findById(story.getId())).thenReturn(Optional.of(story));

        String contentType = exportService.exportStory(story.getId(), ExportFormat.POSTMAN).contentType();

        assertThat(contentType).isEqualTo("application/json");
    }

    @Test
    void testSuiteExportFilenameContainsPostmanExtension() {
        Story story = storyWithApprovedApiTestCase();
        TestSuite suite = story.getTestSuites().getFirst();
        when(testSuiteRepository.findById(suite.getId())).thenReturn(Optional.of(suite));

        String filename = exportService.exportTestSuite(suite.getId(), ExportFormat.POSTMAN).filename();

        assertThat(filename).startsWith("test-suite-");
        assertThat(filename).endsWith(".postman_collection.json");
    }

    // ── Fixtures ──────────────────────────────────────────────────

    private Story storyWithApprovedApiTestCase() {
        Story story = new Story("Checkout payment", StoryType.USER_STORY);
        setId(story, UUID.randomUUID());
        story.setProject(new Project("Checkout Platform", "CHECKOUT"));

        TestSuite suite = new TestSuite("API regression");
        setId(suite, UUID.randomUUID());

        TestCase approved = new TestCase("Verify API endpoint returns 200", TestCaseType.API);
        setId(approved, UUID.randomUUID());
        approved.setReviewStatus(ReviewStatus.APPROVED);
        approved.setDescription("Covers approved API availability check.");
        approved.setTestLayer(TestLayer.API);
        approved.setPriority(Priority.HIGH);
        approved.setRiskLevel(RiskLevel.HIGH);
        approved.setAutomationCandidate(true);
        approved.addStep(new TestStep(1, "Send GET to /health", "Response status is 200"));

        suite.addTestCase(approved);
        story.addTestSuite(suite);
        return story;
    }

    private Story storyWithMixedStatuses() {
        Story story = storyWithApprovedApiTestCase();
        TestSuite suite = story.getTestSuites().getFirst();
        suite.addTestCase(nonApproved("Card payment rejected scenario", ReviewStatus.REJECTED));
        suite.addTestCase(nonApproved("Card payment draft scenario", ReviewStatus.DRAFT));
        suite.addTestCase(nonApproved("Card payment needs-review scenario", ReviewStatus.NEEDS_REVIEW));
        suite.addTestCase(nonApproved("Card payment needs-clarification scenario", ReviewStatus.NEEDS_CLARIFICATION));
        return story;
    }

    private Story storyWithUiLayerTestCase() {
        Story story = new Story("Login story", StoryType.USER_STORY);
        setId(story, UUID.randomUUID());
        story.setProject(new Project("Web Platform", "WEB"));

        TestSuite suite = new TestSuite("UI regression");
        setId(suite, UUID.randomUUID());

        TestCase uiCase = new TestCase("Login via browser UI", TestCaseType.FUNCTIONAL);
        setId(uiCase, UUID.randomUUID());
        uiCase.setReviewStatus(ReviewStatus.APPROVED);
        uiCase.setTestLayer(TestLayer.UI);

        suite.addTestCase(uiCase);
        story.addTestSuite(suite);
        return story;
    }

    private Story storyWithOnlyDraftCases() {
        Story story = new Story("Draft story", StoryType.USER_STORY);
        setId(story, UUID.randomUUID());
        story.setProject(new Project("Platform", "PLT"));

        TestSuite suite = new TestSuite("Draft suite");
        setId(suite, UUID.randomUUID());
        suite.addTestCase(nonApproved("Draft only API test", ReviewStatus.DRAFT));
        story.addTestSuite(suite);
        return story;
    }

    private TestCase nonApproved(String title, ReviewStatus status) {
        TestCase tc = new TestCase(title, TestCaseType.API);
        setId(tc, UUID.randomUUID());
        tc.setReviewStatus(status);
        return tc;
    }

    private void setId(Object entity, UUID id) {
        ReflectionTestUtils.setField(entity, "id", id);
    }
}
